configuration:
  debug-mode: true
  default-name: "default"
  teleport-out-of-the-mine-on-reset: true
  broadcast-on-reset: true
  use-permissions: true
defaults:
  display-name: ""
  blacklist:
    enabled: false
    whitelist: false
    blocks: []
  protection:
    padding: 0
    padding-top: 0
    breaking:
      enabled: true
      blacklist:
        enabled: false
        whitelist: false
        blocks: []
    placement:
      enabled: true
      blacklist:
        enabled: false
        whitelist: false
        blocks: []
    pvp: true
  reset:
    auto:
      reset: true
      reset-time: 15
      warn: true
      warn-times:
      - '5'
    manual:
      cooldown-enabled: true
      cooldown-time: 5
  materials:
    blocks:
    - '1'
    weights:
    - '100'
messages:
  title: "Mine Reset"
  title-on-signs: "Reset"
  manual-mine-reset-successful: "Mine %MINE% was reset!"
  automatic-mine-reset-successful: "Mine %MINE% was reset! Next reset in %TIME% minute(s)."
  automatic-mine-reset-warning: "Mine %MINE% resets in %TIME% minute(s)."
  invalid-command: "Invalid command! Use /mine help for help."
  access-denied: "You do not have permission to do that"
data:
  version: 1.0dev7