configuration:
  version: "2.0.0"
  debug-mode: false
  language: "english"
  use-permissions: true
lag:
  automatic-resets-enabled: true
  check-time-every: 20
  protection-checks-enabled: true
  save-data-on-reset: true
versions:
  check-for-new-versions: true
  check-for-recommended-builds: true
  check-for-development-builds: false
  remind-on-login: true
  permission-node: "minereset.edit"