configuration:
  debug-mode: false
  language: "english"
  use-permissions: true
lag:
  automatic-resets-enabled: true
  check-time-every: 1
  protection-checks-enabled: true
  teleport-out-of-the-mine-on-reset: true
defaults:
  display-name: ""
  silent: false
  blacklist:
    enabled: false
    whitelist: false
    blocks: []
  protection:
    padding: 0
    padding-top: 0
    breaking:
      enabled: false
      blacklist:
        enabled: false
        whitelist: false
        blocks: []
    placement:
      enabled: false
      blacklist:
        enabled: false
        whitelist: false
        blocks: []
    pvp: true
  reset:
    auto:
      reset: true
      reset-time: 15
      warn: true
      warn-times:
      - '5'
  materials:
    blocks:
    - '0'
    weights:
    - '100'