name: MineReset
main: com.wolvencraft.MineReset.MineReset
version: 2.0.0
description: A must-have tool for all prison servers
authors: [bitWolfy, jjkoletar, ProGamerzFTW]
website: http://bit.ly/MineReset
commands:
  mine:
    description: MineReset help
permissions:
  MineReset.*:
    default: op
    children:
      MineReset.normal:
        default: true
        children:
          MineReset.info.time: true
          MineReset.warp.use: true
          MineReset.reset.sign: true
          MineReset.protection.break: true
          MineReset.protection.place: true
          MineReset.protection.bypass: true
      MineReset.admin:
        default: op
        children:
          MineReset.*: true
      MineReset.info.*:
        default: op
        children:
          MineReset.info.all: true
          MineReset.info.time: true
      MineReset.protection.*:
        default: op
        children:
          MineReset.protection.break: true
          MineReset.protection.place: true
          MineReset.protection.pvp: true
          MineReset.protection.bypass: true
      MineReset.reset.*:
        default: op
        children:
          MineReset.reset.manual: true
          MineReset.reset.sign: true
          MineReset.reset.snapshot: true
          MineReset.reset.bypass: true
      MineReset.edit.*:
        default: op
        children:
          MineReset.edit.config: true
          MineReset.edit.info: true
          MineReset.edit.protection: true
          MineReset.edit.save: true
          MineReset.edit.select: true
          MineReset.edit.snapshot: true
          MineReset.edit.sign: true
      MineReset.warp.*:
        default: op
        children:
          MineReset.warp.use: true
          MineReset.warp.set: true