name: MineReset
main: com.wolvencraft.MineReset.MineReset
version: 1.0dev6
commands:
  mine:
    description: MineReset help
permissions:
  MineReset.*:
    description: Gives access to all MineReset commands
    children:
      MineReset.info: true
      MineReset.list: true
      MineReset.warp: true
      MineReset.protection: true
      MineReset.reset: true
      MineReset.edit: true
      MineReset.secret: true
  MineReset.info:
    description: Allows a player to look at the information about a mine
    default: true
  MineReset.list:
    description: Allows a player to look at the list of existing mines
    default: true
  MineReset.warp:
    description: Allows a player to teleport to the mine warp location
    default: true
  MineReset.reset:
    description: Allows a player to reset a mine manually
    default: op
  MineReset.edit:
    description: Allows a player to create and edit mines
    default: op
  MineReset.secret:
    description: Gives access to undocumented commands
    default: op