name: MineReset
main: com.wolvencraft.MineReset.MineReset
version: 0.3
commands:
  mine:
    description: MineReset help
permissions:
  MineReset.*:
    description: Gives access to all MineReset commands
    children:
      MineReset.break: true
      MineReset.help: true
      MineReset.reset: true
      MineReset.info: true
      MineReset.edit: true
  MineReset.info:
    description: Allows a player to look at the information about a mine
    default: true
  MineReset.list:
    description: Allows a player to look at the list of existing mines
    default: true
  MineReset.protection:
    description: Handles whether a player can place and break blocks in the mine
    default: true
  MineReset.reset:
    description: Allows a player to reset a mine manually
    default: op
  MineReset.edit:
    description: Allows a player to create and edit mines
    default: op