name: MineReset
main: com.wolvencraft.MineReset.MineReset
version: 1.1.5
commands:
  mine:
    description: MineReset help
permissions:
  MineReset.*:
    description: Gives access to all MineReset commands
    children:
      MineReset.info: true
      MineReset.list: true
      MineReset.warp: true
      MineReset.protection: true
      MineReset.reset: true
      MineReset.edit: true
      MineReset.secret: true
  MineReset.user:
    description: Gives access to basic MineReset commands
      MineReset.info: true
      MineReset.list: true
      MineReset.warp: true
      MineReset.protection: true
  MineReset.admin:
    description: Gives access to advanced MineReset commands
    children:
      MineReset.user: true
      MineReset.reset: true
      MineReset.edit: true
      MineReset.secret: true
  MineReset.info:
    description: Allows a player to look at the information about a mine
    default: true
  MineReset.list:
    description: Allows a player to look at the list of existing mines
    default: true
  MineReset.warp:
    description: Allows a player to teleport to the mine warp location
    default: true
  MineReset.protection:
    description: Allows a player to break and place blocks in all mines
    children:
      MineReset.protection.break: true
      MineReset.protection.place: true
  MineReset.protection.break:
    description: Allows a player to break blocks in all mines
    default: true
  MineReset.protection.place:
    description: Allows a player to place blocks in all mines
    default: true
  MineReset.reset:
    description: Allows a player to reset a mine manually
    children:
      MineReset.reset.manual: true
      MineReset.reset.sign: true
  MineReset.reset.manual:
    description: Allows a player to reset a mine manually
    default: op
  MineReset.reset.sign:
    description: Allows a player to reset a mine with a sign
    default: op
  MineReset.edit:
    description: Allows a player to create and edit mines
    default: op
  MineReset.secret:
    description: Gives access to undocumented commands
    default: op